### ISSUE TITLE
Complete figures YAML for plates, and add full figures list to objects.yml

### ISSUE THREAD

**Issue by geealbers** [thegetty/cva10#10]
I've added basic YAML entries for all the plate images that include an id, src, and description as in the sample below. The descriptions are just for reference (they won't appear in the catalogue) but include either a full caption or an accession number. The ids are variants of the object accession number with a letter at the end to make them unique. The letter was added arbitrarily, but may actually prove to be in the order they should appear in the book. 

```yaml
  - id: "73AE135-e"
    src: objects/008219F6V1.jpg
    description: "Mixing Vessel with a Dancing Girl; Myson (Greek (Attic), active 500–475 B.C.); Athens, Greece; about 490 B.C.; Terracotta; 35 × 34.5 × 30 cm (13 3/4 × 13 9/16 × 11 13/16 in.); 73.AE.135"

  - id: "76AE13110-a"
    src: objects/00865801.jpg
    description: 76.AE.131.10
```

Using the illustration log and the plate layout pdf (both on the dept. server and in the `transmittal-files` directory of this repo), the goal is to identify which image is which view of the object, and add the description in the illustration log to our YAML file as `alt` text. This will give us some basic alt text for accessibility, and as a way of identifying what image is what.  **You can work in the existing `plate-images` branch rather than creating a new one.**

```yaml
  - id: "86AE205-a"
    src: objects/01404701.jpg
    alt: "One view of a vase, the body depicting two horses and two men"
    description: 86.AE.205

  - id: "86AE205-b"
    src: objects/014047F1V1.jpg
    alt: "The another view of the vase, the body depicting three men, one in clothes"
    description: 86.AE.205
```
Along with completing the figures.yml file, the objects.yml file should also be updated with a corresponding list of figures. I've done catalogue entry 1 as an example. Each figure is represented by its id, and the order they appear in the list is the order they'll appear in the entry page.

```yaml
object_list:
  - id: 1
    plates: 518–20
    accession_number: 86.AE.205
    bareiss_number: 342
    fabric: Athenian
    technique: Red-figure
    shape_name: Krater, Column-
    attribution: Myson
    attributor: J. D. Beazley
    date: -490 to -480
    subject: akontist, athlete, bridle, deer, dog, goat, *halteres*, himation, horse, javelin, jumper, *kentron*, panther, pick, sponge, staff, stick, strigil, trainer
    figure:
      - id: 86AE205-a
      - id: 86AE205-b
      - id: 86AE205-c
      - id: 86AE205-d
      - id: 86AE205-e
      - id: 86AE205-f
      - id: 86AE205-g
      - id: 86AE205-h
      - id: 86AE205-i
```

NOTES: 

- It looks like none of the detail images were supplied by imaging services. For these, please create placeholder yaml entries, like:

```yaml
- id: "86AE205-g"
  src: objects/###.jpg
  alt: "Detail of the three men"
  description: 86.AE.205
```

- The entries in `figures.yml` are grouped by accession number, but not in order of the catalogue entry. And as mentioned before, the letters appended on the end of the IDs was arbitrary, but it looks like they're mostly in order as they should appear in the final publication.
