### ISSUE TITLE
Add links to collection pages

### ISSUE THREAD

**Issue by geealbers** [thegetty/cva10#11]
As in past catalogues, each catalogue entry in the CVA should include a link to the object on the Getty's collection pages. This can be done by adding a `link` entry to each object in the `objects.yml`.

```yaml
  - id: 1
    plates: 518–20
    accession_number: 86.AE.205
    link: "http://www.getty.edu/art/collection/objects/11968/"
```
The URLs used should only ever include the collection object number as in the example above, not the title or other information that may appear when looking at the page online. Such as `http://www.getty.edu/art/collection/objects/11968/attributed-to-myson-attic-red-figure-column-krater-greek-attic-about-480-bc/?artview=dor318674`.
