### ISSUE TITLE
Create objects.yml and individual object entry pages

### ISSUE THREAD

**Issue by geealbers** [thegetty/cva10#2]
Using the `transmittal-files/catalogue.md` file as a source to copy and paste from, a markdown file should be created for each of the 24 catalogue entries, `1.md` is there as a sample. The file name is the entry number, and the page YAML should follow this pattern:

```yaml
number: 1
weight: 101
object:
  - id: 1
type: entry
```
```yaml
number: 2
weight: 102
object:
  - id: 2
type: entry
```

Along with the Markdown files, the object data from `transmittal-files/catalogue.md` should also be added to the `objects.yml` file. Again, the data for entry 1 is there as a sample. For the `figure` just use a placeholder source name based on the accession number of the entry. As in entry 1, when the accession number is 86.AE.205, the yaml would be:

```yaml
figure:
  - src: 86AE205.jpg
```
