### ISSUE TITLE
Add all profile images to the figures.yml and Profiles page

### ISSUE THREAD

**Issue by geealbers** [thegetty/cva10#4]
We need to add the profile images first to the figures.yml file, and then to the Profiles page in the catalogue. A sample for each exists in the repo and all the images are included in the `static/img` directory. The markup for the figures.yml listing:

```yaml
- id: "86AE205-profile"
  src: 86AE205-profile.png
  caption: "Catalogue no. 1"
  alt: "Line drawing profile view of the krater"
```

For the Profiles page, use the `q-figure` shortcode:

```go
{{< q-figure id="86AE205-profile" >}}
```
